import "../styles/fc.scss";
import React from "react";

class SS00 extends React.Component {
    componentDidMount() {
        window.$(".word").flip({ speed: 200 });
    }
    render() {
        return (
            <div>
                <h3>Anglofor</h3>
                <h1>Sveltana L0</h1>
                <section class="words">

                    <div class="word">	<div class="front part part1">	<p>	1	</p>	<div class="rus">	или	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɔr	</div>	<div class="spell">	or	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	2	</p>	<div class="rus">	заяц	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	hɛr	</div>	<div class="spell">	hare	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	3	</p>	<div class="rus">	сюда	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	hir	</div>	<div class="spell">	here	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	4	</p>	<div class="rus">	где	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	wɛr	</div>	<div class="spell">	where	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	5	</p>	<div class="rus">	гусь	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɡus	</div>	<div class="spell">	goose	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	6	</p>	<div class="rus">	гуси	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɡis	</div>	<div class="spell">	geese	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	7	</p>	<div class="rus">	лес	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈfɔrəst	</div>	<div class="spell">	forest	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	8	</p>	<div class="rus">	когда	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	wɛn	</div>	<div class="spell">	when	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	9	</p>	<div class="rus">	скунс	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	skʌŋk	</div>	<div class="spell">	skunk	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	10	</p>	<div class="rus">	бобёр	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈbivər	</div>	<div class="spell">	beaver	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	11	</p>	<div class="rus">	третий	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	θɜrd	</div>	<div class="spell">	third	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	12	</p>	<div class="rus">	кролик	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈræbət	</div>	<div class="spell">	rabbit	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	13	</p>	<div class="rus">	точно	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪɡˈzæktli	</div>	<div class="spell">	exactly	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	14	</p>	<div class="rus">	грузчие	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈloʊdər	</div>	<div class="spell">	loader	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	15	</p>	<div class="rus">	скучный	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈbɔrɪŋ	</div>	<div class="spell">	boring	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	16	</p>	<div class="rus">	2010	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈtwɛnti tɛn	</div>	<div class="spell">	twenty ten	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	17	</p>	<div class="rus">	автобусом	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	baɪ bʌs	</div>	<div class="spell">	by bus	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	18	</p>	<div class="rus">	улучшать	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪmˈpruv	</div>	<div class="spell">	improve	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	19	</p>	<div class="rus">	водопад	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈwɔtərˌfɔl	</div>	<div class="spell">	waterfall	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	20	</p>	<div class="rus">	пеший поход	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ə haɪk	</div>	<div class="spell">	a hike	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	21	</p>	<div class="rus">	я уволилась	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ kwɪt	</div>	<div class="spell">	I quit	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	22	</p>	<div class="rus">	на воле	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪn ðə waɪld	</div>	<div class="spell">	in the wild	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	23	</p>	<div class="rus">	(вот) так	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	laɪk ðɪs	</div>	<div class="spell">	like this	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	24	</p>	<div class="rus">	на автомобиле	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	baɪ kɑr	</div>	<div class="spell">	by car	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	25	</p>	<div class="rus">	2018	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈtwɛnti eɪˈtin	</div>	<div class="spell">	twenty eighteen	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	26	</p>	<div class="rus">	это ветер	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪts ə wɪnd	</div>	<div class="spell">	it’s a wind	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	27	</p>	<div class="rus">	работодатель	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɛmˈplɔɪər	</div>	<div class="spell">	employer	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	28	</p>	<div class="rus">	как высоко?	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	haʊ haɪ?	</div>	<div class="spell">	how high?	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	29	</p>	<div class="rus">	в этом году	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ðɪs jɪrz	</div>	<div class="spell">	this years	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	30	</p>	<div class="rus">	на самом деле	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈækʧuəli	</div>	<div class="spell">	actually	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	31	</p>	<div class="rus">	не соглашаться	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	dɪsəˈɡri	</div>	<div class="spell">	disagree	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	32	</p>	<div class="rus">	заботиться о	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	teɪk kɛr ʌv	</div>	<div class="spell">	take care of	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	33	</p>	<div class="rus">	в моём возрасте	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	æt maɪ eɪʤ	</div>	<div class="spell">	at my age	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	34	</p>	<div class="rus">	да, очень!	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	jɛs, ˈvɛri mʌʧ!	</div>	<div class="spell">	Yes, very much!	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	35	</p>	<div class="rus">	говорить хорошо	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	spik wɛl	</div>	<div class="spell">	speak well	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	36	</p>	<div class="rus">	знаменитый парк	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈfeɪməs pɑrk	</div>	<div class="spell">	famous park	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	37	</p>	<div class="rus">	в особенности	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪn pərˈtɪkjələr	</div>	<div class="spell">	in particular	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	38	</p>	<div class="rus">	горная вершина	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈmaʊntən tɑp	</div>	<div class="spell">	mountain top	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	39	</p>	<div class="rus">	имеется ли ...?	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪz ðɛr … ?	</div>	<div class="spell">	is there … ?	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	40	</p>	<div class="rus">	метро нет	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ðɛr ɪz noʊ ˈsʌˌbweɪ	</div>	<div class="spell">	there is no subway	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	41	</p>	<div class="rus">	чем ..., тем ...	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ði … ði …	</div>	<div class="spell">	the … the …	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	42	</p>	<div class="rus">	когда вы были	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	wɛn ju wɜr	</div>	<div class="spell">	when you were	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	43	</p>	<div class="rus">	с одной стороны	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɑn wʌn hænd	</div>	<div class="spell">	on one hand	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	44	</p>	<div class="rus">	реконструкция	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˌrikənˈstrʌkʃən	</div>	<div class="spell">	reconstruction	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	45	</p>	<div class="rus">	в центре (города)	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪn ˈdaʊnˈtaʊn	</div>	<div class="spell">	in downtown	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	46	</p>	<div class="rus">	в течение 2 лет	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	fɔr tu jɪrz	</div>	<div class="spell">	for two years	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	47	</p>	<div class="rus">	вверх на гору	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ʌp ðə ˈmaʊntən	</div>	<div class="spell">	up the mountain	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	48	</p>	<div class="rus">	вниз с горы	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	daʊn ðə ˈmaʊntən	</div>	<div class="spell">	down the mountain	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	49	</p>	<div class="rus">	ни ... ни ...	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈniðər … nɔr …	</div>	<div class="spell">	neither … nor …	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	50	</p>	<div class="rus">	меня разбудили	</div>	<div class="cefr">	B2 (Ox3K)	</div>	</div>	<div class="back part part2">	<div class="ipa">	ðeɪ woʊk mi ʌp	</div>	<div class="spell">	they woke me up	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	51	</p>	<div class="rus">	поискать в интернете	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	lʊk ɪt ʌp	</div>	<div class="spell">	look it up	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	52	</p>	<div class="rus">	либо ... либо	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈiðər ... ɔr ...	</div>	<div class="spell">	either ... or ...	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	53	</p>	<div class="rus">	они вас уволили	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ðeɪ lɛt ju ɡoʊ	</div>	<div class="spell">	they let you go	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	54	</p>	<div class="rus">	X раз за урок	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ɛks taɪmz pɜr klæs	</div>	<div class="spell">	X times per class	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	55	</p>	<div class="rus">	сколько остановок	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	haʊ ˈmɛni stɑps	</div>	<div class="spell">	how many stops	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	56	</p>	<div class="rus">	тележка для поддонов	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈpælət ʤæk	</div>	<div class="spell">	pallet jack	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	57	</p>	<div class="rus">	он начинает дуть	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ɪt stɑrts tu bloʊ	</div>	<div class="spell">	it starts to blow	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	58	</p>	<div class="rus">	с другой стороны	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ɑn ði ˈʌðər hænd	</div>	<div class="spell">	on the other hand	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	59	</p>	<div class="rus">	какой сейчас год?	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	wɑt jɪr ɪz ɪt?	</div>	<div class="spell">	What year is it?	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	60	</p>	<div class="rus">	мы найдём способ	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	wi wɪl faɪnd ə weɪ	</div>	<div class="spell">	we will find a way	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	61	</p>	<div class="rus">	иностранные языки	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈfɔrən ˈlæŋɡwəʤəz	</div>	<div class="spell">	foreign languages	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	62	</p>	<div class="rus">	одни говорят мне	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	sʌm ˈpipəl tɛl mi	</div>	<div class="spell">	some people tell me	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	63	</p>	<div class="rus">	вы видели оленей?	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	hæv ju sin dɪr?	</div>	<div class="spell">	have you seen deer?	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	64	</p>	<div class="rus">	Шинуки ʃɪˈnʊk 	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ʃɪˈnʊk wɪndz, ʧɪˈnʊks	</div>	<div class="spell">	Chinook winds, Chinooks	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	65	</p>	<div class="rus">	на расстоянии 4 часов	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	fɔr ˈaʊərz əˈweɪ	</div>	<div class="spell">	four hours away	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	66	</p>	<div class="rus">	я делал это сам	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ hæv dʌn ɪt ˌmaɪˈsɛlf	</div>	<div class="spell">	I have done it myself	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	67	</p>	<div class="rus">	я никогда не слышал	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ hæv ˈnɛvər hɜrd	</div>	<div class="spell">	I have never heard	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	68	</p>	<div class="rus">	20 минут пешком	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈtwɛnti ˈmɪnəts ɑn fʊt	</div>	<div class="spell">	twenty minutes on foot	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	69	</p>	<div class="rus">	я знаю каково это	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ noʊ wɑt ɪts laɪk	</div>	<div class="spell">	I know what it’s like	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	70	</p>	<div class="rus">	самое страшное животное	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈskɛriəst ˈænəməl	</div>	<div class="spell">	scariest animal	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	71	</p>	<div class="rus">	я так много слышу о	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ hir soʊ mʌʧ əˈbaʊt	</div>	<div class="spell">	I hear so much about	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	72	</p>	<div class="rus">	потора года назад	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	wʌn ænd ə hæf jɪrz əˈɡoʊ	</div>	<div class="spell">	one and a half years ago	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	73	</p>	<div class="rus">	я никогда не был там	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ hæv ˈnɛvər bɪn ðɛr	</div>	<div class="spell">	I have never been there	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	74	</p>	<div class="rus">	либо в 5, либо в 7	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈiðər æt faɪv ɔr æt ˈsɛvən	</div>	<div class="spell">	either at five or at seven	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	75	</p>	<div class="rus">	увидеть медведя на воле	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	si ə bɛr ɪn ðə waɪld	</div>	<div class="spell">	see a bear in the wild	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	76	</p>	<div class="rus">	покупать, купила, купленный	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	baɪ, bɑt, bɑt	</div>	<div class="spell">	buy, bought, bought	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	77	</p>	<div class="rus">	как сказать "магазин"?	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	haʊ du ju seɪ "магазин"?	</div>	<div class="spell">	how do you say "магазин"?	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	78	</p>	<div class="rus">	пособие по безработице	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ɛmˈplɔɪmənt ɪnˈʃʊrəns (i-aɪ)	</div>	<div class="spell">	employment insurance (EI)	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	79	</p>	<div class="rus">	мне здесь очень нравится	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	aɪ laɪk ɪt hir ˈvɛri mʌʧ	</div>	<div class="spell">	I like it here very much	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	80	</p>	<div class="rus">	я не очень хорошо пишу	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	maɪ ˈraɪtɪŋ ˈɪzənt ˈvɛri ɡʊd	</div>	<div class="spell">	my writing isn’t very good	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	81	</p>	<div class="rus">	чем больше ..., тем легче ...	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ðə mɔr … ði ˈiziər …	</div>	<div class="spell">	the more … the easier …	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	82	</p>	<div class="rus">	больше всего бояться пауков	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	bi moʊst əˈfreɪd ʌv ˈspaɪdərz	</div>	<div class="spell">	be most afraid of spiders	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	83	</p>	<div class="rus">	мы поехали туда на микроавтобусе	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	wi wɛnt ðɛr ɪn ə væn	</div>	<div class="spell">	we went there in a van	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	84	</p>	<div class="rus">	-25 градусов по Цельсию	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	ˈmaɪnəs ˈtwɛnti faɪv dɪˈɡriz ˈsɛlsiəs	</div>	<div class="spell">	minus twenty five degrees Celsius	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	85	</p>	<div class="rus">	от 40 до 50 часов в неделю	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	frʌm ˈfɔrti tu ˈfɪfti ˈaʊərz ə wik	</div>	<div class="spell">	from forty to fifty hours a week	</div>	</div>	</div>
                    <div class="word">	<div class="front part part1">	<p>	86	</p>	<div class="rus">	вам приходилось поднимать тяжести?	</div>	<div class="cefr">		</div>	</div>	<div class="back part part2">	<div class="ipa">	dɪd ju hæv tu lɪft ˈhɛvi θɪŋz?	</div>	<div class="spell">	did you have to lift heavy things?	</div>	</div>	</div>

                </section>

            </div>
        );
    }


}



export default SS00;